# Generated by Django 5.2.17 on 2026-09-06 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        help_text="Community or group that this post belongs to.",
                        max_length=120,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Optional city or area associated with the post.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["city", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "city"), name="unique_location_per_city"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("learning", "Learning"),
                            ("budgeting", "Budgeting"),
                            ("diet", "Diet & Wellness"),
                            ("social", "Social"),
                            ("general", "General Self-Care"),
                            ("exploration", "Exploration"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custom_category",
                    models.CharField(
                        blank=True,
                        help_text="Only used if category is set to 'Other'.",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional location for exploration-based quests.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quests",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="QuestCompletion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_status", models.BooleanField(default=False)),
                (
                    "quest_date",
                    models.DateField(
                        help_text="Date the user chose or started this quest."
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "quest",
                    models.ForeignKey(
                        help_text="Protected so historical completion records are preserved if a quest is deleted.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completions",
                        to="core.quest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-quest_date"],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("sticker", "Sticker"),
                            ("font", "Font"),
                            ("frame", "Frame"),
                            ("background", "Background"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Quests that can potentially unlock this reward.",
                        related_name="possible_rewards",
                        to="core.quest",
                    ),
                ),
            ],
            options={
                "ordering": ["item_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserReward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_time", models.DateTimeField(auto_now_add=True)),
                (
                    "reward",
                    models.ForeignKey(
                        help_text="The reward earned by the user.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earned_by",
                        to="core.reward",
                    ),
                ),
                (
                    "unlocked_by_completion",
                    models.ForeignKey(
                        help_text="The completed quest that unlocked this reward.",
                        limit_choices_to={"completed_status": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_rewards",
                        to="core.questcompletion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-unlocked_time"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decorations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Cosmetic rewards used to decorate this journal entry.",
                        related_name="used_in_journals",
                        to="core.userreward",
                    ),
                ),
            ],
            options={
                "ordering": ["-time"],
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_from", "user_to"), name="unique_friend_request"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="quest",
            constraint=models.UniqueConstraint(
                fields=("title", "category"), name="unique_quest_title_per_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="questcompletion",
            constraint=models.UniqueConstraint(
                fields=("user", "quest", "quest_date"),
                name="unique_completion_per_user_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="reward",
            constraint=models.UniqueConstraint(
                fields=("name", "item_type"), name="unique_reward_definition"
            ),
        ),
        migrations.AddConstraint(
            model_name="userreward",
            constraint=models.UniqueConstraint(
                fields=("user", "reward"), name="unique_user_reward"
            ),
        ),
    ]
