# Generated by Django 5.2.17 on 2026-09-06 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="decorations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cosmetic rewards earned by this user and used to decorate the journal.",
                related_name="used_in_journals",
                to="core.userreward",
            ),
        ),
        migrations.AlterField(
            model_name="userreward",
            name="unlocked_by_completion",
            field=models.ForeignKey(
                blank=True,
                help_text="The completed quest that unlocked this reward.",
                limit_choices_to={"completed_status": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlocked_rewards",
                to="core.questcompletion",
            ),
        ),
        migrations.AlterField(
            model_name="userreward",
            name="user",
            field=models.ForeignKey(
                help_text="The user who earned this reward.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rewards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
