# Generated by Django 5.2.17 on 2026-09-06 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_journal_decorations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="location",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
