# Generated by Django 6.1.1 on 2026-10-08 15:25

import django.db.models.deletion
from django.db import migrations, models


# Design files for the rewards that already exist (inside the static folder)
REWARD_ASSETS = {
    ("Stay Hydrated Sticker", "sticker"): "rewards/stickers/stay-hydrated.svg",
    ("Nature Background", "background"): "rewards/backgrounds/nature.svg",
    ("Cloud Background", "background"): "rewards/backgrounds/clouds.svg",
    ("Smily face frame", "frame"): "rewards/frames/smiley.svg",
    ("Cool Font", "font"): "rewards/fonts/caveat.woff2",
}


def set_reward_assets(apps, schema_editor):
    Reward = apps.get_model("core", "Reward")

    for (name, item_type), asset in REWARD_ASSETS.items():
        Reward.objects.filter(name=name, item_type=item_type, asset="").update(asset=asset)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_userreward_per_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="background",
            field=models.ForeignKey(
                blank=True,
                help_text="Background reward the page is drawn on.",
                limit_choices_to={"item_type": "background"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.reward",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="font",
            field=models.ForeignKey(
                blank=True,
                help_text="Font reward the entry is written in.",
                limit_choices_to={"item_type": "font"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.reward",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="frame",
            field=models.ForeignKey(
                blank=True,
                help_text="Frame reward drawn around the page.",
                limit_choices_to={"item_type": "frame"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.reward",
            ),
        ),
        migrations.AddField(
            model_name="reward",
            name="asset",
            field=models.CharField(
                blank=True,
                help_text="Design file inside the static folder, e.g. rewards/stickers/stay-hydrated.svg. Stickers: square SVG/PNG; backgrounds and frames: 4:3 landscape PNG/SVG; fonts: .woff2.",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="JournalSticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x",
                    models.FloatField(
                        help_text="Horizontal position of the sticker's center, 0-100% of the page width."
                    ),
                ),
                (
                    "y",
                    models.FloatField(
                        help_text="Vertical position of the sticker's center, 0-100% of the page height."
                    ),
                ),
                (
                    "rotation",
                    models.IntegerField(default=0, help_text="Rotation in degrees."),
                ),
                ("scale", models.FloatField(default=1.0)),
                (
                    "layer",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Stacking order; higher layers are drawn on top.",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stickers",
                        to="core.journal",
                    ),
                ),
                (
                    "user_reward",
                    models.OneToOneField(
                        help_text="The sticker copy used for this placement.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement",
                        to="core.userreward",
                    ),
                ),
            ],
            options={
                "ordering": ["layer", "id"],
            },
        ),
        migrations.RunPython(set_reward_assets, migrations.RunPython.noop),
    ]
